#!/bin/bash


# Host IP address should be to local machine.  These should also be in the /etc/hosts file
# TODO: automate getting local IP to pass to container to talk to Access-Platform initiated containers.
# Alternative is to have the metadatabus be one of the containers launched from within the Access-Platform compose...


docker build -t cihm-metadatabus . &&
  docker run -it -v $(pwd)/CIHM-Meta:/home/tdr/CIHM-Meta -v $(pwd)/CIHM-Swift:/home/tdr/CIHM-Swift \
  --add-host "couch-dev.canadiana.ca:192.168.142.38" --add-host "swift-dev.canadiana.ca:192.168.142.38" \
  -v "/var/log/tdr:/var/log/tdr" -v "/var/lock/tdr:/var/lock/tdr" \
  --env-file ./.env  cihm-metadatabus bash

