#!/bin/bash

docker build -t cihm-metadatabus . &&
  docker run -it -v $(pwd)/CIHM-Meta:/home/tdr/CIHM-Meta -v "/etc/canadiana/tdr/tdr.conf:/home/tdr/tdr.conf" -v "/var/log/tdr:/var/log/tdr" -v "/var/lock/tdr:/var/lock/tdr"  cihm-metadatabus bash

